name: flutter_app_qiita
description: A new Flutter application.


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  http: ^0.13.4
  intl: ^0.17.0
  cached_network_image: ^3.2.0
  flutter_dotenv: ^5.0.2
  shared_preferences: ^2.0.15
  webview_flutter_plus: ^0.3.0+2
  custom_refresh_indicator: ^1.2.1
  package_info_plus: ^1.4.2
  modal_bottom_sheet: ^2.1.0


  flutter:
    sdk: flutter

  google_fonts: ^2.3.1

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0

flutter:


  uses-material-design: true

  assets:
    - images/qiita.png
    - images/network_error.png
    - images/default_icon_image.png
    - .env






